/* The following code was generated by JFlex 1.4.3 on 27/02/18 12:57 AM */


package Analizadores.LenguajeCHTML;
import Estructuras.*;
import java.util.LinkedList;
import java_cup.runtime.*;

import Errores.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/02/18 12:57 AM from the specification file
 * <tt>src/Analizadores/LenguajeCHTML/Lex_HTML.flex</tt>
 */
public class AL_HTML implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\0\1\3\1\1\16\7\4\0\1\3\1\0"+
    "\1\10\1\0\1\6\5\0\1\16\1\15\1\0\1\13\1\5\1\12"+
    "\12\4\1\0\1\17\1\11\1\20\1\14\2\0\1\32\1\51\1\33"+
    "\1\26\1\43\1\23\1\40\1\42\1\35\1\53\1\36\1\34\1\47"+
    "\1\25\1\24\1\41\1\46\1\27\1\44\1\31\1\30\1\37\1\6"+
    "\1\50\1\6\1\45\4\0\1\52\1\0\1\32\1\51\1\33\1\26"+
    "\1\43\1\23\1\40\1\42\1\35\1\53\1\36\1\34\1\47\1\25"+
    "\1\24\1\41\1\46\1\27\1\44\1\31\1\30\1\37\1\6\1\50"+
    "\1\6\1\45\1\21\1\7\1\22\1\0\41\7\2\0\4\6\4\0"+
    "\1\6\2\0\1\7\7\0\1\6\4\0\1\6\5\0\27\6\1\0"+
    "\37\6\1\0\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6\1\0"+
    "\1\6\21\0\160\7\5\6\1\0\2\6\2\0\4\6\10\0\1\6"+
    "\1\0\3\6\1\0\1\6\1\0\24\6\1\0\123\6\1\0\213\6"+
    "\1\0\5\7\2\0\236\6\11\0\46\6\2\0\1\6\7\0\47\6"+
    "\7\0\1\6\1\0\55\7\1\0\1\7\1\0\2\7\1\0\2\7"+
    "\1\0\1\7\10\0\33\6\5\0\3\6\15\0\5\7\6\0\1\6"+
    "\4\0\13\7\5\0\53\6\25\7\12\4\4\0\2\6\1\7\143\6"+
    "\1\0\1\6\10\7\1\0\6\7\2\6\2\7\1\0\4\7\2\6"+
    "\12\4\3\6\2\0\1\6\17\0\1\7\1\6\1\7\36\6\33\7"+
    "\2\0\131\6\13\7\1\6\16\0\12\4\41\6\11\7\2\6\4\0"+
    "\1\6\5\0\26\6\4\7\1\6\11\7\1\6\3\7\1\6\5\7"+
    "\22\0\31\6\3\7\104\0\1\6\1\0\13\6\67\0\33\7\1\0"+
    "\4\7\66\6\3\7\1\6\22\7\1\6\7\7\12\6\2\7\2\0"+
    "\12\4\1\0\7\6\1\0\7\6\1\0\3\7\1\0\10\6\2\0"+
    "\2\6\2\0\26\6\1\0\7\6\1\0\1\6\3\0\4\6\2\0"+
    "\1\7\1\6\7\7\2\0\2\7\2\0\3\7\1\6\10\0\1\7"+
    "\4\0\2\6\1\0\3\6\2\7\2\0\12\4\4\6\7\0\1\6"+
    "\5\0\3\7\1\0\6\6\4\0\2\6\2\0\26\6\1\0\7\6"+
    "\1\0\2\6\1\0\2\6\1\0\2\6\2\0\1\7\1\0\5\7"+
    "\4\0\2\7\2\0\3\7\3\0\1\7\7\0\4\6\1\0\1\6"+
    "\7\0\12\4\2\7\3\6\1\7\13\0\3\7\1\0\11\6\1\0"+
    "\3\6\1\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0"+
    "\1\7\1\6\10\7\1\0\3\7\1\0\3\7\2\0\1\6\17\0"+
    "\2\6\2\7\2\0\12\4\1\0\1\6\17\0\3\7\1\0\10\6"+
    "\2\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6"+
    "\2\0\1\7\1\6\7\7\2\0\2\7\2\0\3\7\10\0\2\7"+
    "\4\0\2\6\1\0\3\6\2\7\2\0\12\4\1\0\1\6\20\0"+
    "\1\7\1\6\1\0\6\6\3\0\3\6\1\0\4\6\3\0\2\6"+
    "\1\0\1\6\1\0\2\6\3\0\2\6\3\0\3\6\3\0\14\6"+
    "\4\0\5\7\3\0\3\7\1\0\4\7\2\0\1\6\6\0\1\7"+
    "\16\0\12\4\11\0\1\6\7\0\3\7\1\0\10\6\1\0\3\6"+
    "\1\0\27\6\1\0\12\6\1\0\5\6\3\0\1\6\7\7\1\0"+
    "\3\7\1\0\4\7\7\0\2\7\1\0\2\6\6\0\2\6\2\7"+
    "\2\0\12\4\22\0\2\7\1\0\10\6\1\0\3\6\1\0\27\6"+
    "\1\0\12\6\1\0\5\6\2\0\1\7\1\6\7\7\1\0\3\7"+
    "\1\0\4\7\7\0\2\7\7\0\1\6\1\0\2\6\2\7\2\0"+
    "\12\4\1\0\2\6\17\0\2\7\1\0\10\6\1\0\3\6\1\0"+
    "\51\6\2\0\1\6\7\7\1\0\3\7\1\0\4\7\1\6\10\0"+
    "\1\7\10\0\2\6\2\7\2\0\12\4\12\0\6\6\2\0\2\7"+
    "\1\0\22\6\3\0\30\6\1\0\11\6\1\0\1\6\2\0\7\6"+
    "\3\0\1\7\4\0\6\7\1\0\1\7\1\0\10\7\22\0\2\7"+
    "\15\0\60\6\1\7\2\6\7\7\4\0\10\6\10\7\1\0\12\4"+
    "\47\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6\2\0\1\6"+
    "\6\0\4\6\1\0\7\6\1\0\3\6\1\0\1\6\1\0\1\6"+
    "\2\0\2\6\1\0\4\6\1\7\2\6\6\7\1\0\2\7\1\6"+
    "\2\0\5\6\1\0\1\6\1\0\6\7\2\0\12\4\2\0\4\6"+
    "\40\0\1\6\27\0\2\7\6\0\12\4\13\0\1\7\1\0\1\7"+
    "\1\0\1\7\4\0\2\7\10\6\1\0\44\6\4\0\24\7\1\0"+
    "\2\7\5\6\13\7\1\0\44\7\11\0\1\7\71\0\53\6\24\7"+
    "\1\6\12\4\6\0\6\6\4\7\4\6\3\7\1\6\3\7\2\6"+
    "\7\7\3\6\4\7\15\6\14\7\1\6\1\7\12\4\4\7\2\0"+
    "\46\6\1\0\1\6\5\0\1\6\2\0\53\6\1\0\u014d\6\1\0"+
    "\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0\51\6\1\0"+
    "\4\6\2\0\41\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0"+
    "\4\6\2\0\17\6\1\0\71\6\1\0\4\6\2\0\103\6\2\0"+
    "\3\7\40\0\20\6\20\0\125\6\14\0\u026c\6\2\0\21\6\1\0"+
    "\32\6\5\0\113\6\3\0\3\6\17\0\15\6\1\0\4\6\3\7"+
    "\13\0\22\6\3\7\13\0\22\6\2\7\14\0\15\6\1\0\3\6"+
    "\1\0\2\7\14\0\64\6\40\7\3\0\1\6\3\0\2\6\1\7"+
    "\2\0\12\4\41\0\3\7\2\0\12\4\6\0\130\6\10\0\51\6"+
    "\1\7\1\6\5\0\106\6\12\0\35\6\3\0\14\7\4\0\14\7"+
    "\12\0\12\4\36\6\2\0\5\6\13\0\54\6\4\0\21\7\7\6"+
    "\2\7\6\0\12\4\46\0\27\6\5\7\4\0\65\6\12\7\1\0"+
    "\35\7\2\0\1\7\12\4\6\0\12\4\15\0\1\6\130\0\5\7"+
    "\57\6\21\7\7\6\4\0\12\4\21\0\11\7\14\0\3\7\36\6"+
    "\15\7\2\6\12\4\54\6\16\7\14\0\44\6\24\7\10\0\12\4"+
    "\3\0\3\6\12\4\44\6\122\0\3\7\1\0\25\7\4\6\1\7"+
    "\4\6\3\7\2\6\11\0\300\6\47\7\25\0\4\7\u0116\6\2\0"+
    "\6\6\2\0\46\6\2\0\6\6\2\0\10\6\1\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\37\6\2\0\65\6\1\0\7\6\1\0"+
    "\1\6\3\0\3\6\1\0\7\6\3\0\4\6\2\0\6\6\4\0"+
    "\15\6\5\0\3\6\1\0\7\6\16\0\5\7\32\0\5\7\20\0"+
    "\2\6\23\0\1\6\13\0\5\7\5\0\6\7\1\0\1\6\15\0"+
    "\1\6\20\0\15\6\3\0\33\6\25\0\15\7\4\0\1\7\3\0"+
    "\14\7\21\0\1\6\4\0\1\6\2\0\12\6\1\0\1\6\3\0"+
    "\5\6\6\0\1\6\1\0\1\6\1\0\1\6\1\0\4\6\1\0"+
    "\13\6\2\0\4\6\5\0\5\6\4\0\1\6\21\0\51\6\u0a77\0"+
    "\57\6\1\0\57\6\1\0\205\6\6\0\4\6\3\7\2\6\14\0"+
    "\46\6\1\0\1\6\5\0\1\6\2\0\70\6\7\0\1\6\17\0"+
    "\1\7\27\6\11\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\40\7"+
    "\57\0\1\6\u01d5\0\3\6\31\0\11\6\6\7\1\0\5\6\2\0"+
    "\5\6\4\0\126\6\2\0\2\7\2\0\3\6\1\0\132\6\1\0"+
    "\4\6\5\0\51\6\3\0\136\6\21\0\33\6\65\0\20\6\u0200\0"+
    "\u19b6\6\112\0\u51cd\6\63\0\u048d\6\103\0\56\6\2\0\u010d\6\3\0"+
    "\20\6\12\4\2\6\24\0\57\6\1\7\4\0\12\7\1\0\31\6"+
    "\7\0\1\7\120\6\2\7\45\0\11\6\2\0\147\6\2\0\4\6"+
    "\1\0\4\6\14\0\13\6\115\0\12\6\1\7\3\6\1\7\4\6"+
    "\1\7\27\6\5\7\20\0\1\6\7\0\64\6\14\0\2\7\62\6"+
    "\21\7\13\0\12\4\6\0\22\7\6\6\3\0\1\6\4\0\12\4"+
    "\34\6\10\7\2\0\27\6\15\7\14\0\35\6\3\0\4\7\57\6"+
    "\16\7\16\0\1\6\12\4\46\0\51\6\16\7\11\0\3\6\1\7"+
    "\10\6\2\7\2\0\12\4\6\0\27\6\3\0\1\6\1\7\4\0"+
    "\60\6\1\7\1\6\3\7\2\6\2\7\5\6\2\7\1\6\1\7"+
    "\1\6\30\0\3\6\2\0\13\6\5\7\2\0\3\6\2\7\12\0"+
    "\6\6\2\0\6\6\2\0\6\6\11\0\7\6\1\0\7\6\221\0"+
    "\43\6\10\7\1\0\2\7\2\0\12\4\6\0\u2ba4\6\14\0\27\6"+
    "\4\0\61\6\u2104\0\u016e\6\2\0\152\6\46\0\7\6\14\0\5\6"+
    "\5\0\1\6\1\7\12\6\1\0\15\6\1\0\5\6\1\0\1\6"+
    "\1\0\2\6\1\0\2\6\1\0\154\6\41\0\u016b\6\22\0\100\6"+
    "\2\0\66\6\50\0\15\6\3\0\20\7\20\0\7\7\14\0\2\6"+
    "\30\0\3\6\31\0\1\6\6\0\5\6\1\0\207\6\2\0\1\7"+
    "\4\0\1\6\13\0\12\4\7\0\32\6\4\0\1\6\1\0\32\6"+
    "\13\0\131\6\3\0\6\6\2\0\6\6\2\0\6\6\2\0\3\6"+
    "\3\0\2\6\3\0\2\6\22\0\3\7\1\0\1\7\2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\0\1\2\3\3\1\4\1\2\1\5\2\2"+
    "\1\6\1\7\1\2\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\12\5\1\0\1\1\1\0\1\16\13\0\1\17"+
    "\7\5\1\20\3\5\1\21\1\22\5\5\6\0\1\23"+
    "\2\0\1\24\6\0\21\5\17\0\1\5\1\0\3\5"+
    "\1\25\1\5\1\26\1\5\1\27\7\5\10\0\1\30"+
    "\7\0\1\31\11\0\1\32\2\5\1\33\1\5\1\34"+
    "\3\5\1\35\1\36\1\37\5\0\1\40\1\0\1\41"+
    "\1\42\4\0\1\43\3\0\1\44\14\0\1\45\4\5"+
    "\1\46\11\0\1\47\3\0\1\50\1\51\1\52\6\0"+
    "\1\53\1\0\1\54\5\0\1\55\3\5\1\0\1\56"+
    "\3\0\1\57\2\0\1\60\1\61\1\62\2\0\1\63"+
    "\12\0\1\64\1\65\1\5\1\56\13\0\1\66\6\0"+
    "\1\67\3\0\1\70\3\0\1\71\1\0\1\72\1\73"+
    "\3\0\1\74\2\0\1\75\1\76\1\77\1\0\1\100"+
    "\1\101\1\102\1\103\2\0\1\104\1\105\1\0\1\106"+
    "\1\107\1\0\1\110\2\0\1\111";

  private static int [] zzUnpackAction() {
    int [] result = new int[321];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\130\0\334\0\u0108"+
    "\0\u0134\0\u0160\0\u018c\0\130\0\130\0\u01b8\0\130\0\130"+
    "\0\130\0\130\0\130\0\130\0\u01e4\0\u0210\0\u023c\0\u0268"+
    "\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u0108\0\u0108"+
    "\0\u0160\0\130\0\u039c\0\u03c8\0\u03f4\0\u0420\0\u044c\0\u0478"+
    "\0\u04a4\0\u04d0\0\u04fc\0\u0528\0\u01b8\0\130\0\u0554\0\u0580"+
    "\0\u05ac\0\u05d8\0\u0604\0\u0630\0\u065c\0\u0134\0\u0688\0\u06b4"+
    "\0\u06e0\0\u0134\0\u0134\0\u070c\0\u0738\0\u0764\0\u0790\0\u07bc"+
    "\0\u07e8\0\u0814\0\u0840\0\u086c\0\u0898\0\u08c4\0\130\0\u08f0"+
    "\0\u091c\0\130\0\u0948\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24"+
    "\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58\0\u0b84"+
    "\0\u0bb0\0\u0bdc\0\u0c08\0\u0c34\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4"+
    "\0\u0d10\0\u0d3c\0\u0d68\0\u0d94\0\u0dc0\0\u0dec\0\u0e18\0\u0e44"+
    "\0\u0e70\0\u0e9c\0\u0ec8\0\u0ef4\0\u0f20\0\u0f4c\0\u0f78\0\u0fa4"+
    "\0\u0fd0\0\u0ffc\0\u1028\0\u1054\0\u1080\0\u0134\0\u10ac\0\u0134"+
    "\0\u10d8\0\u0134\0\u1104\0\u1130\0\u115c\0\u1188\0\u11b4\0\u11e0"+
    "\0\u120c\0\u1238\0\u1264\0\u1290\0\u12bc\0\u12e8\0\u1314\0\u1340"+
    "\0\u136c\0\u1398\0\u13c4\0\u13f0\0\u141c\0\u1448\0\u1474\0\u14a0"+
    "\0\u14cc\0\u0134\0\u14f8\0\u1524\0\u1550\0\u157c\0\u15a8\0\u15d4"+
    "\0\u1600\0\u162c\0\u1658\0\u0134\0\u1684\0\u16b0\0\u0134\0\u16dc"+
    "\0\u0134\0\u1708\0\u1734\0\u1760\0\u0134\0\u0134\0\u0134\0\u178c"+
    "\0\u17b8\0\u17e4\0\u1810\0\u183c\0\130\0\u1868\0\130\0\u1894"+
    "\0\u18c0\0\u18ec\0\u1918\0\u1944\0\130\0\u1970\0\u199c\0\u19c8"+
    "\0\130\0\u19f4\0\u1a20\0\u1a4c\0\u1a78\0\u1aa4\0\u1ad0\0\u1afc"+
    "\0\u1b28\0\u1b54\0\u1b80\0\u1bac\0\u1bd8\0\u0134\0\u1c04\0\u1c30"+
    "\0\u1c5c\0\u1c88\0\u0134\0\u1cb4\0\u1ce0\0\u1d0c\0\u1d38\0\u1d64"+
    "\0\u1d90\0\u1dbc\0\u1de8\0\u1e14\0\130\0\u1e40\0\u1e6c\0\u1e98"+
    "\0\130\0\130\0\130\0\u1ec4\0\u1ef0\0\u1f1c\0\u1f48\0\u1f74"+
    "\0\u1fa0\0\130\0\u1fcc\0\130\0\u1ff8\0\u2024\0\u2050\0\u207c"+
    "\0\u20a8\0\u0134\0\u20d4\0\u2100\0\u212c\0\u2158\0\u1238\0\u2184"+
    "\0\u21b0\0\u21dc\0\130\0\u2208\0\u2234\0\130\0\130\0\130"+
    "\0\u2260\0\u228c\0\130\0\u22b8\0\u22e4\0\u2310\0\u233c\0\u2368"+
    "\0\u2394\0\u23c0\0\u23ec\0\u2418\0\u2444\0\u0134\0\u0134\0\u2470"+
    "\0\130\0\u249c\0\u24c8\0\u24f4\0\u2520\0\u254c\0\u2578\0\u25a4"+
    "\0\u25d0\0\u25fc\0\u2628\0\u2654\0\130\0\u2680\0\u26ac\0\u26d8"+
    "\0\u2704\0\u2730\0\u275c\0\u0134\0\u2788\0\u27b4\0\u27e0\0\130"+
    "\0\u280c\0\u2838\0\u2864\0\130\0\u2890\0\130\0\130\0\u28bc"+
    "\0\u28e8\0\u2914\0\130\0\u2940\0\u296c\0\130\0\130\0\130"+
    "\0\u2998\0\130\0\130\0\130\0\130\0\u29c4\0\u29f0\0\130"+
    "\0\130\0\u2a1c\0\130\0\130\0\u2a48\0\130\0\u2a74\0\u2aa0"+
    "\0\130";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[321];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\11\1\27\1\30"+
    "\2\11\1\31\1\32\1\11\1\33\1\11\1\34\1\35"+
    "\10\11\1\36\2\11\1\3\1\4\1\5\1\6\10\3"+
    "\1\16\37\3\56\0\1\6\52\0\1\6\56\0\1\7"+
    "\1\37\52\0\1\40\53\0\1\11\1\0\2\11\13\0"+
    "\31\11\10\41\1\42\43\41\12\0\1\43\10\0\1\44"+
    "\1\45\4\0\1\46\1\0\1\47\1\0\1\50\3\0"+
    "\1\51\1\0\1\52\1\53\4\0\1\54\2\0\11\55"+
    "\1\56\42\55\4\0\1\11\1\0\2\11\13\0\1\11"+
    "\1\57\10\11\1\60\16\11\4\0\1\11\1\0\2\11"+
    "\13\0\16\11\1\61\12\11\4\0\1\11\1\0\2\11"+
    "\13\0\20\11\1\62\10\11\4\0\1\11\1\0\2\11"+
    "\13\0\5\11\1\63\23\11\4\0\1\11\1\0\2\11"+
    "\13\0\2\11\1\64\6\11\1\65\17\11\4\0\1\11"+
    "\1\0\2\11\13\0\6\11\1\66\1\11\1\67\1\70"+
    "\6\11\1\71\5\11\1\72\2\11\4\0\1\11\1\0"+
    "\2\11\13\0\3\11\1\73\16\11\1\74\1\11\1\75"+
    "\4\11\4\0\1\11\1\0\2\11\13\0\7\11\1\76"+
    "\21\11\4\0\1\11\1\0\2\11\13\0\4\11\1\77"+
    "\24\11\4\0\1\11\1\0\2\11\13\0\1\11\1\100"+
    "\27\11\12\0\1\101\76\0\1\102\57\0\1\103\44\0"+
    "\1\104\10\0\1\105\40\0\1\106\1\107\1\110\7\0"+
    "\1\111\6\0\1\112\51\0\1\113\36\0\1\114\46\0"+
    "\1\115\60\0\1\116\6\0\1\117\36\0\1\120\33\0"+
    "\1\11\1\0\2\11\13\0\2\11\1\121\26\11\4\0"+
    "\1\11\1\0\2\11\13\0\2\11\1\122\6\11\1\123"+
    "\17\11\4\0\1\11\1\0\2\11\13\0\10\11\1\124"+
    "\20\11\4\0\1\11\1\0\2\11\13\0\4\11\1\125"+
    "\24\11\4\0\1\11\1\0\2\11\13\0\6\11\1\126"+
    "\22\11\4\0\1\11\1\0\2\11\13\0\10\11\1\127"+
    "\20\11\4\0\1\11\1\0\2\11\13\0\6\11\1\130"+
    "\3\11\1\131\16\11\4\0\1\11\1\0\2\11\13\0"+
    "\21\11\1\132\7\11\4\0\1\11\1\0\2\11\13\0"+
    "\12\11\1\133\16\11\4\0\1\11\1\0\2\11\13\0"+
    "\2\11\1\134\26\11\4\0\1\11\1\0\2\11\13\0"+
    "\23\11\1\135\5\11\4\0\1\11\1\0\2\11\13\0"+
    "\7\11\1\136\21\11\4\0\1\11\1\0\2\11\13\0"+
    "\11\11\1\137\17\11\4\0\1\11\1\0\2\11\13\0"+
    "\5\11\1\140\23\11\4\0\1\11\1\0\2\11\13\0"+
    "\6\11\1\141\22\11\13\0\1\142\65\0\1\143\6\0"+
    "\1\144\52\0\1\145\71\0\1\146\52\0\1\147\46\0"+
    "\1\150\63\0\1\151\31\0\1\152\54\0\1\153\46\0"+
    "\1\154\62\0\1\155\53\0\1\156\54\0\1\157\47\0"+
    "\1\160\26\0\1\11\1\0\2\11\13\0\3\11\1\161"+
    "\25\11\4\0\1\11\1\0\2\11\3\0\1\162\7\0"+
    "\31\11\4\0\1\11\1\0\2\11\13\0\27\11\1\163"+
    "\1\11\4\0\1\11\1\0\2\11\13\0\12\11\1\164"+
    "\16\11\4\0\1\11\1\0\2\11\13\0\20\11\1\165"+
    "\10\11\4\0\1\11\1\0\2\11\13\0\7\11\1\166"+
    "\21\11\4\0\1\11\1\0\2\11\13\0\17\11\1\167"+
    "\11\11\4\0\1\11\1\0\2\11\13\0\1\11\1\170"+
    "\27\11\4\0\1\11\1\0\2\11\13\0\2\11\1\171"+
    "\26\11\4\0\1\11\1\0\2\11\13\0\21\11\1\172"+
    "\7\11\4\0\1\11\1\0\2\11\13\0\10\11\1\173"+
    "\20\11\4\0\1\11\1\0\2\11\13\0\6\11\1\174"+
    "\22\11\4\0\1\11\1\0\2\11\13\0\5\11\1\175"+
    "\23\11\4\0\1\11\1\0\2\11\13\0\15\11\1\176"+
    "\13\11\4\0\1\11\1\0\2\11\13\0\1\11\1\177"+
    "\27\11\4\0\1\11\1\0\2\11\13\0\16\11\1\200"+
    "\12\11\4\0\1\11\1\0\2\11\13\0\1\11\1\201"+
    "\27\11\13\202\1\203\40\202\13\0\1\204\112\0\1\205"+
    "\36\0\1\206\52\0\1\207\50\0\1\210\51\0\1\211"+
    "\56\0\1\212\70\0\1\213\44\0\1\214\56\0\1\215"+
    "\42\0\1\216\52\0\1\217\47\0\1\220\52\0\1\221"+
    "\33\0\1\11\1\0\2\11\13\0\1\11\1\222\27\11"+
    "\23\0\1\223\1\224\4\0\1\225\1\0\1\226\1\0"+
    "\1\227\3\0\1\230\1\0\1\231\1\232\4\0\1\233"+
    "\6\0\1\11\1\0\2\11\13\0\6\11\1\234\22\11"+
    "\4\0\1\11\1\0\2\11\13\0\1\11\1\235\27\11"+
    "\4\0\1\11\1\0\2\11\13\0\10\11\1\236\20\11"+
    "\4\0\1\11\1\0\2\11\13\0\1\11\1\237\27\11"+
    "\4\0\1\11\1\0\2\11\13\0\20\11\1\240\10\11"+
    "\4\0\1\11\1\0\2\11\13\0\13\11\1\241\15\11"+
    "\4\0\1\11\1\0\2\11\13\0\4\11\1\242\24\11"+
    "\4\0\1\11\1\0\2\11\13\0\12\11\1\243\16\11"+
    "\4\0\1\11\1\0\2\11\13\0\20\11\1\244\10\11"+
    "\4\0\1\11\1\0\2\11\13\0\4\11\1\245\24\11"+
    "\4\0\1\11\1\0\2\11\13\0\1\11\1\246\27\11"+
    "\4\0\1\11\1\0\2\11\13\0\2\11\1\247\26\11"+
    "\13\202\1\250\52\202\1\251\1\203\40\202\23\0\1\252"+
    "\5\0\1\253\1\0\1\254\51\0\1\255\46\0\1\256"+
    "\61\0\1\257\45\0\1\260\70\0\1\261\64\0\1\262"+
    "\35\0\1\263\62\0\1\264\44\0\1\265\52\0\1\266"+
    "\44\0\1\267\54\0\1\270\53\0\1\271\63\0\1\272"+
    "\57\0\1\273\44\0\1\274\10\0\1\275\41\0\1\276"+
    "\1\277\16\0\1\300\51\0\1\301\36\0\1\302\46\0"+
    "\1\303\67\0\1\304\36\0\1\305\33\0\1\11\1\0"+
    "\2\11\13\0\2\11\1\306\26\11\4\0\1\11\1\0"+
    "\2\11\13\0\17\11\1\307\11\11\4\0\1\11\1\0"+
    "\2\11\13\0\7\11\1\310\21\11\4\0\1\11\1\0"+
    "\2\11\13\0\7\11\1\311\21\11\4\0\1\11\1\0"+
    "\2\11\13\0\20\11\1\312\10\11\4\0\1\11\1\0"+
    "\2\11\13\0\2\11\1\313\26\11\12\202\1\314\1\250"+
    "\52\202\1\315\1\250\40\202\35\0\1\316\50\0\1\317"+
    "\51\0\1\320\1\321\1\322\7\0\1\323\6\0\1\324"+
    "\27\0\1\325\100\0\1\326\25\0\1\327\60\0\1\330"+
    "\36\0\1\331\64\0\1\332\71\0\1\333\23\0\1\334"+
    "\103\0\1\335\44\0\1\336\52\0\1\337\71\0\1\340"+
    "\52\0\1\341\17\0\1\342\112\0\1\343\14\0\1\344"+
    "\71\0\1\345\46\0\1\346\62\0\1\347\54\0\1\350"+
    "\47\0\1\351\26\0\1\11\1\0\2\11\13\0\7\11"+
    "\1\352\21\11\4\0\1\11\1\0\2\11\13\0\3\11"+
    "\1\353\25\11\4\0\1\11\1\0\2\11\13\0\3\11"+
    "\1\354\25\11\4\0\1\11\1\0\2\11\13\0\4\11"+
    "\1\355\24\11\12\202\1\356\1\250\53\202\1\250\1\357"+
    "\37\202\34\0\1\360\70\0\1\361\45\0\1\362\24\0"+
    "\1\363\112\0\1\364\31\0\1\365\36\0\1\366\71\0"+
    "\1\367\35\0\1\370\102\0\1\371\33\0\1\372\57\0"+
    "\1\373\76\0\1\374\36\0\1\375\52\0\1\376\50\0"+
    "\1\377\54\0\1\u0100\61\0\1\u0101\56\0\1\u0102\42\0"+
    "\1\u0103\46\0\1\u0104\52\0\1\u0105\33\0\1\11\1\0"+
    "\2\11\13\0\1\11\1\u0106\27\11\4\0\1\11\1\0"+
    "\2\11\13\0\1\11\1\u0107\27\11\4\0\1\11\1\0"+
    "\2\11\13\0\3\11\1\u0108\25\11\13\202\1\250\1\u0109"+
    "\37\202\52\0\1\u010a\35\0\1\u010b\46\0\1\u010c\56\0"+
    "\1\u010d\70\0\1\u010e\54\0\1\u010f\40\0\1\u0110\47\0"+
    "\1\u0111\46\0\1\u0112\61\0\1\u0113\45\0\1\u0114\43\0"+
    "\1\u0115\35\0\1\u0116\44\0\1\u0117\44\0\1\u0118\52\0"+
    "\1\u0119\45\0\1\u011a\53\0\1\u011b\32\0\1\11\1\0"+
    "\2\11\13\0\7\11\1\u011c\21\11\31\0\1\u011d\54\0"+
    "\1\u011e\62\0\1\u011f\26\0\1\u0120\73\0\1\u0121\50\0"+
    "\1\u0122\47\0\1\u0123\42\0\1\u0124\64\0\1\u0125\42\0"+
    "\1\u0126\53\0\1\u0127\35\0\1\u0128\32\0\1\u0129\47\0"+
    "\1\u012a\42\0\1\u012b\102\0\1\u012c\53\0\1\u012d\24\0"+
    "\1\u012e\53\0\1\u012f\53\0\1\u0130\63\0\1\u0131\43\0"+
    "\1\u0132\63\0\1\u0133\43\0\1\u0134\53\0\1\u0135\71\0"+
    "\1\u0136\64\0\1\u0137\24\0\1\u0138\53\0\1\u0139\66\0"+
    "\1\u013a\40\0\1\u013b\53\0\1\u013c\107\0\1\u013d\17\0"+
    "\1\u013e\70\0\1\u013f\46\0\1\u0140\43\0\1\u0141\37\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10956];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\0\1\11\2\1\1\11\5\1\2\11\1\1"+
    "\6\11\12\1\1\0\1\1\1\0\1\11\13\0\1\11"+
    "\22\1\6\0\1\11\2\0\1\11\6\0\21\1\17\0"+
    "\1\1\1\0\17\1\10\0\1\1\7\0\1\1\11\0"+
    "\14\1\5\0\1\11\1\0\1\11\1\1\4\0\1\11"+
    "\3\0\1\11\14\0\6\1\11\0\1\11\3\0\3\11"+
    "\6\0\1\11\1\0\1\11\5\0\4\1\1\0\1\1"+
    "\3\0\1\11\2\0\3\11\2\0\1\11\12\0\3\1"+
    "\1\11\13\0\1\11\6\0\1\1\3\0\1\11\3\0"+
    "\1\11\1\0\2\11\3\0\1\11\2\0\3\11\1\0"+
    "\4\11\2\0\2\11\1\0\2\11\1\0\1\11\2\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[321];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    StringBuilder string = new StringBuilder();

static LinkedList<Erro_r> listaErrores= new LinkedList();

  public void adderror(int fila, int columna, String valor){
       Erro_r n = new Erro_r(fila,columna,valor,"");
       listaErrores.add(n);
  }

/*public void agregar(String Token,String Lexema,int Fila, int Columna){
  Simbolo simbolo= new Simbolo(Token,Lexema,Fila,Columna);
  TablaSimbolos.add(simbolo);	
}
  

public LinkedList<Simbolo> retornarTablaSimbolos(){
     return AnalizadorLexico.TablaSimbolos;
}*/

public LinkedList<Erro_r> retornarErrores(){       
	return null;//AnalizadorLexico.listaErrores;
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AL_HTML(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AL_HTML(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2298) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 43: 
          { return new Symbol(sym.FCT, new token(yycolumn, yyline, yytext()));
          }
        case 74: break;
        case 73: 
          { return new Symbol(sym.FCAJA_TEXTO, new token(yycolumn, yyline, yytext()));
          }
        case 75: break;
        case 32: 
          { return new Symbol(sym.IFIL_T2, new token(yycolumn, yyline, yytext()));
          }
        case 76: break;
        case 20: 
          { return new Symbol(sym.ICB2, new token(yycolumn, yyline, yytext()));
          }
        case 77: break;
        case 41: 
          { return new Symbol(sym.IIMAGEN, new token(yycolumn, yyline, yytext()));
          }
        case 78: break;
        case 61: 
          { return new Symbol(sym.FBOTON, new token(yycolumn, yyline, yytext()));
          }
        case 79: break;
        case 31: 
          { return new Symbol(sym.TBOTON, new token(yycolumn, yyline, yytext()));
          }
        case 80: break;
        case 53: 
          { return new Symbol(sym.CENT, new token(yycolumn, yyline, yytext()));
          }
        case 81: break;
        case 71: 
          { return new Symbol(sym.FTEXTO_A, new token(yycolumn, yyline, yytext()));
          }
        case 82: break;
        case 24: 
          { return new Symbol(sym.ICAJA, new token(yycolumn, yyline, yytext()));
          }
        case 83: break;
        case 5: 
          { return new Symbol(sym.I_D, new token(yycolumn, yyline, yytext()));
          }
        case 84: break;
        case 16: 
          { return new Symbol(sym.ICT, new token(yycolumn, yyline, yytext()));
          }
        case 85: break;
        case 45: 
          { return new Symbol(sym.DER, new token(yycolumn, yyline, yytext()));
          }
        case 86: break;
        case 28: 
          { return new Symbol(sym.CLICK, new token(yycolumn, yyline, yytext()));
          }
        case 87: break;
        case 47: 
          { return new Symbol(sym.FCT2, new token(yycolumn, yyline, yytext()));
          }
        case 88: break;
        case 37: 
          { return new Symbol(sym.IOPCION, new token(yycolumn, yyline, yytext()));
          }
        case 89: break;
        case 2: 
          { System.out.println(yyline+","+yycolumn+"=["+yytext()+"],"+yychar); adderror(yyline,yycolumn,yytext());
          }
        case 90: break;
        case 34: 
          { return new Symbol(sym.ITEXTO, new token(yycolumn, yyline, yytext()));
          }
        case 91: break;
        case 14: 
          { return new Symbol(sym.STRING_LITERAL, new token(yycolumn, yyline, yytext()));
          }
        case 92: break;
        case 22: 
          { return new Symbol(sym.ALTO, new token(yycolumn, yyline, yytext()));
          }
        case 93: break;
        case 4: 
          { return new Symbol(sym.NUM, new token(yycolumn, yyline, yytext()));
          }
        case 94: break;
        case 54: 
          { return new Symbol(sym.FCAJA, new token(yycolumn, yyline, yytext()));
          }
        case 95: break;
        case 69: 
          { return new Symbol(sym.FENLACE, new token(yycolumn, yyline, yytext()));
          }
        case 96: break;
        case 23: 
          { return new Symbol(sym.CCSS, new token(yycolumn, yyline, yytext()));
          }
        case 97: break;
        case 70: 
          { return new Symbol(sym.FCUERPO, new token(yycolumn, yyline, yytext()));
          }
        case 98: break;
        case 15: 
          { return new Symbol(sym.EXPLICIT, new token(yycolumn, yyline, yytext()));
          }
        case 99: break;
        case 21: 
          { return new Symbol(sym.RUTA, new token(yycolumn, yyline, yytext()));
          }
        case 100: break;
        case 7: 
          { return new Symbol(sym.MENOS, new token(yycolumn, yyline, yytext()));
          }
        case 101: break;
        case 18: 
          { return new Symbol(sym.ID, new token(yycolumn, yyline, yytext()));
          }
        case 102: break;
        case 64: 
          { return new Symbol(sym.FCHTML, new token(yycolumn, yyline, yytext()));
          }
        case 103: break;
        case 9: 
          { return new Symbol(sym.POR, new token(yycolumn, yyline, yytext()));
          }
        case 104: break;
        case 60: 
          { return new Symbol(sym.FPANEL, new token(yycolumn, yyline, yytext()));
          }
        case 105: break;
        case 63: 
          { return new Symbol(sym.FTABLA2, new token(yycolumn, yyline, yytext()));
          }
        case 106: break;
        case 62: 
          { return new Symbol(sym.FFIL_T2, new token(yycolumn, yyline, yytext()));
          }
        case 107: break;
        case 11: 
          { return new Symbol(sym.IGUAL, new token(yycolumn, yyline, yytext()));
          }
        case 108: break;
        case 27: 
          { return new Symbol(sym.ANCHO, new token(yycolumn, yyline, yytext()));
          }
        case 109: break;
        case 66: 
          { return new Symbol(sym.ISALTOF, new token(yycolumn, yyline, yytext()));
          }
        case 110: break;
        case 65: 
          { return new Symbol(sym.ICAJA_TEXTO, new token(yycolumn, yyline, yytext()));
          }
        case 111: break;
        case 36: 
          { return new Symbol(sym.IBOTON, new token(yycolumn, yyline, yytext()));
          }
        case 112: break;
        case 25: 
          { return new Symbol(sym.FONDO, new token(yycolumn, yyline, yytext()));
          }
        case 113: break;
        case 33: 
          { return new Symbol(sym.ITABLA, new token(yycolumn, yyline, yytext()));
          }
        case 114: break;
        case 39: 
          { return new Symbol(sym.IOPCION2, new token(yycolumn, yyline, yytext()));
          }
        case 115: break;
        case 57: 
          { return new Symbol(sym.FFIL_T, new token(yycolumn, yyline, yytext()));
          }
        case 116: break;
        case 51: 
          { return new Symbol(sym.ISPINNER, new token(yycolumn, yyline, yytext()));
          }
        case 117: break;
        case 48: 
          { return new Symbol(sym.FCB2, new token(yycolumn, yyline, yytext()));
          }
        case 118: break;
        case 30: 
          { return new Symbol(sym.GRUPO, new token(yycolumn, yyline, yytext()));
          }
        case 119: break;
        case 68: 
          { return new Symbol(sym.FIMAGEN, new token(yycolumn, yyline, yytext()));
          }
        case 120: break;
        case 1: 
          { return new Symbol(sym.DECIMAL, new token(yycolumn, yyline, yytext()));
          }
        case 121: break;
        case 67: 
          { return new Symbol(sym.FOPCION, new token(yycolumn, yyline, yytext()));
          }
        case 122: break;
        case 10: 
          { return new Symbol(sym.PYC, new token(yycolumn, yyline, yytext()));
          }
        case 123: break;
        case 55: 
          { return new Symbol(sym.IZQ, new token(yycolumn, yyline, yytext()));
          }
        case 124: break;
        case 19: 
          { return new Symbol(sym.ICT2, new token(yycolumn, yyline, yytext()));
          }
        case 125: break;
        case 38: 
          { return new Symbol(sym.TIMAGEN, new token(yycolumn, yyline, yytext()));
          }
        case 126: break;
        case 52: 
          { return new Symbol(sym.ALINEADO, new token(yycolumn, yyline, yytext()));
          }
        case 127: break;
        case 12: 
          { return new Symbol(sym.ALLA, new token(yycolumn, yyline, yytext()));
          }
        case 128: break;
        case 40: 
          { return new Symbol(sym.ICHTML, new token(yycolumn, yyline, yytext()));
          }
        case 129: break;
        case 13: 
          { return new Symbol(sym.CLLA, new token(yycolumn, yyline, yytext()));
          }
        case 130: break;
        case 59: 
          { return new Symbol(sym.FTEXTO, new token(yycolumn, yyline, yytext()));
          }
        case 131: break;
        case 6: 
          { return new Symbol(sym.DIV, new token(yycolumn, yyline, yytext()));
          }
        case 132: break;
        case 35: 
          { return new Symbol(sym.IPANEL, new token(yycolumn, yyline, yytext()));
          }
        case 133: break;
        case 72: 
          { return new Symbol(sym.FSPINNER, new token(yycolumn, yyline, yytext()));
          }
        case 134: break;
        case 49: 
          { return new Symbol(sym.ITEXTO_A, new token(yycolumn, yyline, yytext()));
          }
        case 135: break;
        case 8: 
          { return new Symbol(sym.MAS, new token(yycolumn, yyline, yytext()));
          }
        case 136: break;
        case 44: 
          { return new Symbol(sym.FCB, new token(yycolumn, yyline, yytext()));
          }
        case 137: break;
        case 42: 
          { return new Symbol(sym.IENLACE, new token(yycolumn, yyline, yytext()));
          }
        case 138: break;
        case 50: 
          { return new Symbol(sym.ICUERPO, new token(yycolumn, yyline, yytext()));
          }
        case 139: break;
        case 46: 
          { System.out.println("Comentario:\n"+ yytext());
          }
        case 140: break;
        case 56: 
          { return new Symbol(sym.FCAJA2, new token(yycolumn, yyline, yytext()));
          }
        case 141: break;
        case 3: 
          { /* ignorar */
          }
        case 142: break;
        case 29: 
          { return new Symbol(sym.VALOR, new token(yycolumn, yyline, yytext()));
          }
        case 143: break;
        case 58: 
          { return new Symbol(sym.FTABLA, new token(yycolumn, yyline, yytext()));
          }
        case 144: break;
        case 26: 
          { return new Symbol(sym.IFIL_T, new token(yycolumn, yyline, yytext()));
          }
        case 145: break;
        case 17: 
          { return new Symbol(sym.ICB, new token(yycolumn, yyline, yytext()));
          }
        case 146: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
