
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 27 03:16:56 CST 2018
//----------------------------------------------------

package Analizadores.LenguajeCHTML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ICHTML = 49;
  public static final int IBOTON = 34;
  public static final int FTABLA = 39;
  public static final int FTEXTO = 31;
  public static final int FCAJA = 45;
  public static final int EXPLICIT = 27;
  public static final int ICUERPO = 51;
  public static final int IFIL_T2 = 54;
  public static final int DER = 25;
  public static final int POR = 4;
  public static final int ALTO = 19;
  public static final int ITEXTO_A = 40;
  public static final int FIMAGEN = 33;
  public static final int FENLACE = 37;
  public static final int NUM = 6;
  public static final int ICT = 62;
  public static final int IOPCION2 = 69;
  public static final int IOPCION = 68;
  public static final int FFIL_T = 55;
  public static final int ITABLA = 38;
  public static final int IGUAL = 10;
  public static final int ICB = 57;
  public static final int CENT = 26;
  public static final int FCT = 63;
  public static final int FCAJA_TEXTO = 43;
  public static final int RUTA = 14;
  public static final int ITEXTO = 30;
  public static final int DECIMAL = 7;
  public static final int FSPINNER = 47;
  public static final int DIV = 5;
  public static final int FPANEL = 29;
  public static final int FCB = 60;
  public static final int MENOS = 3;
  public static final int ANCHO = 20;
  public static final int MAS = 2;
  public static final int ICAJA = 44;
  public static final int ICAJA_TEXTO = 42;
  public static final int STRING_LITERAL = 23;
  public static final int ALLA = 11;
  public static final int EOF = 0;
  public static final int IZQ = 24;
  public static final int PYC = 9;
  public static final int IIMAGEN = 32;
  public static final int CLLA = 12;
  public static final int GRUPO = 18;
  public static final int FCHTML = 50;
  public static final int IENLACE = 36;
  public static final int CCSS = 22;
  public static final int FCB2 = 66;
  public static final int error = 1;
  public static final int ALINEADO = 21;
  public static final int FBOTON = 35;
  public static final int TIMAGEN = 65;
  public static final int ID = 17;
  public static final int CLICK = 15;
  public static final int IFIL_T = 53;
  public static final int ISALTOF = 48;
  public static final int FTEXTO_A = 41;
  public static final int FCUERPO = 52;
  public static final int ICB2 = 58;
  public static final int FCT2 = 67;
  public static final int TBOTON = 64;
  public static final int FFIL_T2 = 56;
  public static final int VALOR = 16;
  public static final int FTABLA2 = 61;
  public static final int ICT2 = 59;
  public static final int IPANEL = 28;
  public static final int FCAJA2 = 71;
  public static final int I_D = 8;
  public static final int FOPCION = 70;
  public static final int ISPINNER = 46;
  public static final int FONDO = 13;
}

