
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 08 08:38:17 CST 2018
//----------------------------------------------------

package Analizadores.LenguajeCJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 47;
  public static final int CASO = 34;
  public static final int POT = 7;
  public static final int POR = 5;
  public static final int MENSAJE = 42;
  public static final int IMPRIMIR = 39;
  public static final int OBSERVADOR = 45;
  public static final int SI = 31;
  public static final int DOCUMENTO = 43;
  public static final int FUNCION = 40;
  public static final int CPAR = 24;
  public static final int OBTENER = 44;
  public static final int MAYQ = 13;
  public static final int CLLA = 26;
  public static final int BOOLEAN_LITERAL = 53;
  public static final int NOT = 19;
  public static final int AND = 17;
  public static final int MENQ = 11;
  public static final int IGUAL = 22;
  public static final int SINO = 32;
  public static final int APAR = 23;
  public static final int COMS = 56;
  public static final int OR = 18;
  public static final int MIENTRAS = 37;
  public static final int DATETIME_LITERAL = 55;
  public static final int DIV = 6;
  public static final int ALLA = 25;
  public static final int NUM = 49;
  public static final int DIMV = 48;
  public static final int ATEXTO = 30;
  public static final int PTO = 52;
  public static final int DECIMAL = 50;
  public static final int EOF = 0;
  public static final int ACORCH = 27;
  public static final int SETELEMENTO = 46;
  public static final int error = 1;
  public static final int CCORCH = 28;
  public static final int COMA = 2;
  public static final int MENIQ = 12;
  public static final int DIF = 16;
  public static final int ADD = 9;
  public static final int MENOS = 4;
  public static final int MOD = 8;
  public static final int IG_IG = 15;
  public static final int MAYIQ = 14;
  public static final int SELECCIONA = 33;
  public static final int DETENER = 38;
  public static final int I_D = 51;
  public static final int PARA = 36;
  public static final int RETORNAR = 41;
  public static final int CONTEO = 29;
  public static final int DSPTS = 21;
  public static final int DEFECTO = 35;
  public static final int SUB = 10;
  public static final int DATE_LITERAL = 54;
  public static final int PYC = 20;
  public static final int MAS = 3;
}

