
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 15 09:20:21 CST 2018
//----------------------------------------------------

package Analizadores;

import Estructuras.*;
import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import Errores.Erro_r;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu Feb 15 09:20:21 CST 2018
  */
public class AS_HTML extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AS_HTML() {super();}

  /** Constructor which sets the default scanner. */
  public AS_HTML(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AS_HTML(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\122\000\002\002\004\000\002\002\003\000\002\052" +
    "\002\000\002\003\010\000\002\053\002\000\002\004\006" +
    "\000\002\054\002\000\002\004\007\000\002\004\004\000" +
    "\002\006\004\000\002\006\010\000\002\055\002\000\002" +
    "\006\013\000\002\013\005\000\002\013\004\000\002\015" +
    "\003\000\002\015\003\000\002\015\003\000\002\016\010" +
    "\000\002\017\010\000\002\022\007\000\002\014\010\000" +
    "\002\056\002\000\002\014\013\000\002\012\024\000\002" +
    "\010\011\000\002\010\010\000\002\020\005\000\002\020" +
    "\004\000\002\021\006\000\002\021\010\000\002\021\010" +
    "\000\002\021\010\000\002\021\010\000\002\021\006\000" +
    "\002\021\010\000\002\021\010\000\002\021\010\000\002" +
    "\021\010\000\002\021\003\000\002\040\006\000\002\040" +
    "\005\000\002\041\005\000\002\041\004\000\002\047\006" +
    "\000\002\042\006\000\002\042\005\000\002\043\005\000" +
    "\002\043\004\000\002\044\006\000\002\044\006\000\002" +
    "\046\006\000\002\046\005\000\002\045\006\000\002\045" +
    "\005\000\002\023\006\000\002\023\005\000\002\025\002" +
    "\000\002\025\003\000\002\026\005\000\002\026\004\000" +
    "\002\024\003\000\002\024\003\000\002\024\003\000\002" +
    "\024\003\000\002\024\003\000\002\024\003\000\002\024" +
    "\003\000\002\024\003\000\002\027\005\000\002\030\007" +
    "\000\002\031\005\000\002\032\005\000\002\033\005\000" +
    "\002\034\005\000\002\035\005\000\002\036\005\000\002" +
    "\051\004\000\002\051\003\000\002\050\003\000\002\050" +
    "\010\000\002\050\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\364\000\004\075\006\001\002\000\004\002\366\001" +
    "\002\000\004\002\000\001\002\000\004\027\007\001\002" +
    "\000\004\074\010\001\002\000\004\075\011\001\002\000" +
    "\010\030\uffff\031\uffff\052\uffff\001\002\000\010\030\014" +
    "\031\015\052\013\001\002\000\004\074\365\001\002\000" +
    "\004\074\304\001\002\000\024\074\uffc8\103\026\104\024" +
    "\105\040\106\025\107\030\110\032\111\031\112\033\001" +
    "\002\000\004\002\ufffe\001\002\000\024\074\uffc7\103\026" +
    "\104\024\105\040\106\025\107\030\110\032\111\031\112" +
    "\033\001\002\000\004\020\uffbf\001\002\000\004\020\301" +
    "\001\002\000\004\020\uffc0\001\002\000\004\020\uffbe\001" +
    "\002\000\004\021\275\001\002\000\004\021\273\001\002" +
    "\000\004\021\271\001\002\000\004\020\uffc2\001\002\000" +
    "\004\021\267\001\002\000\004\021\265\001\002\000\004" +
    "\021\263\001\002\000\004\021\261\001\002\000\004\020" +
    "\uffbd\001\002\000\004\020\uffc1\001\002\000\004\020\uffc3" +
    "\001\002\000\004\020\uffc4\001\002\000\004\021\257\001" +
    "\002\000\004\074\042\001\002\000\004\075\ufffb\001\002" +
    "\000\004\075\045\001\002\000\004\002\ufffa\001\002\000" +
    "\032\033\053\034\062\035\057\036\060\037\050\040\055" +
    "\044\054\045\064\046\063\050\051\051\056\054\252\001" +
    "\002\000\004\075\047\001\002\000\032\033\053\034\062" +
    "\035\057\036\060\037\050\040\055\044\054\045\064\046" +
    "\063\050\051\051\056\054\061\001\002\000\024\074\uffc8" +
    "\103\026\104\024\105\040\106\025\107\030\110\032\111" +
    "\031\112\033\001\002\000\024\074\uffc8\103\026\104\024" +
    "\105\040\106\025\107\030\110\032\111\031\112\033\001" +
    "\002\000\004\075\uffe6\001\002\000\024\074\uffc8\103\026" +
    "\104\024\105\040\106\025\107\030\110\032\111\031\112" +
    "\033\001\002\000\024\074\uffc8\103\026\104\024\105\040" +
    "\106\025\107\030\110\032\111\031\112\033\001\002\000" +
    "\024\074\uffc8\103\026\104\024\105\040\106\025\107\030" +
    "\110\032\111\031\112\033\001\002\000\004\075\uffda\001" +
    "\002\000\024\074\uffc8\103\026\104\024\105\040\106\025" +
    "\107\030\110\032\111\031\112\033\001\002\000\024\074" +
    "\uffc8\103\026\104\024\105\040\106\025\107\030\110\032" +
    "\111\031\112\033\001\002\000\004\074\104\001\002\000" +
    "\024\074\uffc8\103\026\104\024\105\040\106\025\107\030" +
    "\110\032\111\031\112\033\001\002\000\024\074\uffc8\103" +
    "\026\104\024\105\040\106\025\107\030\110\032\111\031" +
    "\112\033\001\002\000\024\074\uffc8\103\026\104\024\105" +
    "\040\106\025\107\030\110\032\111\031\112\033\001\002" +
    "\000\004\074\066\001\002\000\004\075\067\001\002\000" +
    "\004\070\070\001\002\000\004\074\071\001\002\000\004" +
    "\075\uffdd\001\002\000\004\074\073\001\002\000\004\075" +
    "\074\001\002\000\004\071\075\001\002\000\004\074\076" +
    "\001\002\000\004\075\uffdc\001\002\000\004\074\100\001" +
    "\002\000\004\075\101\001\002\000\004\057\102\001\002" +
    "\000\004\074\103\001\002\000\004\075\uffe3\001\002\000" +
    "\004\075\105\001\002\000\004\052\106\001\002\000\004" +
    "\074\107\001\002\000\004\002\uffe8\001\002\000\004\074" +
    "\111\001\002\000\004\075\112\001\002\000\004\061\113" +
    "\001\002\000\004\074\114\001\002\000\004\075\uffe1\001" +
    "\002\000\004\074\116\001\002\000\004\075\117\001\002" +
    "\000\004\060\120\001\002\000\004\074\121\001\002\000" +
    "\004\075\uffe2\001\002\000\004\074\123\001\002\000\004" +
    "\075\125\001\002\000\004\075\214\001\002\000\006\041" +
    "\131\063\130\001\002\000\004\075\uffdf\001\002\000\004" +
    "\075\uffd6\001\002\000\004\074\213\001\002\000\024\074" +
    "\uffc8\103\026\104\024\105\040\106\025\107\030\110\032" +
    "\111\031\112\033\001\002\000\004\074\133\001\002\000" +
    "\004\075\136\001\002\000\004\075\207\001\002\000\004" +
    "\075\uffd5\001\002\000\010\042\140\043\142\064\141\001" +
    "\002\000\004\075\uffd1\001\002\000\024\074\uffc8\103\026" +
    "\104\024\105\040\106\025\107\030\110\032\111\031\112" +
    "\033\001\002\000\004\074\174\001\002\000\024\074\uffc8" +
    "\103\026\104\024\105\040\106\025\107\030\110\032\111" +
    "\031\112\033\001\002\000\004\074\144\001\002\000\012" +
    "\012\147\035\145\036\151\075\152\001\002\000\024\074" +
    "\uffc8\103\026\104\024\105\040\106\025\107\030\110\032" +
    "\111\031\112\033\001\002\000\004\075\uffcf\001\002\000" +
    "\012\012\uffb2\035\uffb2\036\uffb2\075\uffb2\001\002\000\012" +
    "\012\uffb3\035\uffb3\036\uffb3\075\uffb3\001\002\000\024\074" +
    "\uffc8\103\026\104\024\105\040\106\025\107\030\110\032" +
    "\111\031\112\033\001\002\000\004\066\160\001\002\000" +
    "\012\012\147\035\145\036\151\075\155\001\002\000\012" +
    "\012\uffb4\035\uffb4\036\uffb4\075\uffb4\001\002\000\004\066" +
    "\156\001\002\000\004\074\157\001\002\000\004\075\uffcc" +
    "\001\002\000\004\074\161\001\002\000\004\075\uffcb\001" +
    "\002\000\004\074\163\001\002\000\004\075\164\001\002" +
    "\000\004\061\165\001\002\000\004\074\166\001\002\000" +
    "\012\012\uffb1\035\uffb1\036\uffb1\075\uffb1\001\002\000\004" +
    "\074\170\001\002\000\004\075\171\001\002\000\004\060" +
    "\172\001\002\000\004\074\173\001\002\000\012\012\uffb0" +
    "\035\uffb0\036\uffb0\075\uffb0\001\002\000\004\075\uffd3\001" +
    "\002\000\004\074\176\001\002\000\012\012\147\035\145" +
    "\036\151\075\200\001\002\000\004\075\uffd0\001\002\000" +
    "\004\065\205\001\002\000\012\012\147\035\145\036\151" +
    "\075\202\001\002\000\004\065\203\001\002\000\004\074" +
    "\204\001\002\000\004\075\uffce\001\002\000\004\074\206" +
    "\001\002\000\004\075\uffcd\001\002\000\010\042\140\043" +
    "\142\064\211\001\002\000\004\075\uffd2\001\002\000\004" +
    "\074\212\001\002\000\004\075\uffd4\001\002\000\004\075" +
    "\uffd8\001\002\000\006\041\131\063\216\001\002\000\004" +
    "\075\uffd7\001\002\000\004\074\217\001\002\000\004\075" +
    "\uffd9\001\002\000\004\074\221\001\002\000\004\075\222" +
    "\001\002\000\004\067\223\001\002\000\004\074\224\001" +
    "\002\000\004\075\uffde\001\002\000\004\074\226\001\002" +
    "\000\004\075\227\001\002\000\032\033\053\034\062\035" +
    "\057\036\060\037\050\040\055\044\054\045\064\046\063" +
    "\050\051\051\056\056\235\001\002\000\004\075\232\001" +
    "\002\000\004\075\uffe4\001\002\000\032\033\053\034\062" +
    "\035\057\036\060\037\050\040\055\044\054\045\064\046" +
    "\063\050\051\051\056\056\233\001\002\000\004\074\234" +
    "\001\002\000\004\075\uffca\001\002\000\004\074\237\001" +
    "\002\000\004\075\uffe5\001\002\000\004\075\uffc9\001\002" +
    "\000\004\074\241\001\002\000\004\075\242\001\002\000" +
    "\004\073\243\001\002\000\004\074\244\001\002\000\004" +
    "\075\uffdb\001\002\000\004\074\246\001\002\000\004\075" +
    "\247\001\002\000\004\062\250\001\002\000\004\074\251" +
    "\001\002\000\004\075\uffe0\001\002\000\004\074\253\001" +
    "\002\000\004\075\254\001\002\000\004\052\255\001\002" +
    "\000\004\074\256\001\002\000\004\002\uffe7\001\002\000" +
    "\004\114\260\001\002\000\004\020\uffba\001\002\000\004" +
    "\114\262\001\002\000\004\020\uffb5\001\002\000\004\114" +
    "\264\001\002\000\004\020\uffb7\001\002\000\004\114\266" +
    "\001\002\000\004\020\uffb6\001\002\000\004\114\270\001" +
    "\002\000\004\020\uffb8\001\002\000\004\114\272\001\002" +
    "\000\004\020\uffbc\001\002\000\004\114\274\001\002\000" +
    "\004\020\uffb9\001\002\000\004\114\276\001\002\000\004" +
    "\023\277\001\002\000\004\024\300\001\002\000\004\020" +
    "\uffbb\001\002\000\024\074\uffc5\103\uffc5\104\uffc5\105\uffc5" +
    "\106\uffc5\107\uffc5\110\uffc5\111\uffc5\112\uffc5\001\002\000" +
    "\004\020\303\001\002\000\024\074\uffc6\103\uffc6\104\uffc6" +
    "\105\uffc6\106\uffc6\107\uffc6\110\uffc6\111\uffc6\112\uffc6\001" +
    "\002\000\004\075\ufffd\001\002\000\004\075\307\001\002" +
    "\000\004\002\ufffc\001\002\000\012\032\320\053\352\076" +
    "\316\100\313\001\002\000\004\075\311\001\002\000\012" +
    "\032\320\053\315\076\316\100\313\001\002\000\004\002" +
    "\ufff8\001\002\000\024\074\uffc8\103\026\104\024\105\040" +
    "\106\025\107\030\110\032\111\031\112\033\001\002\000" +
    "\004\075\ufff1\001\002\000\004\074\334\001\002\000\024" +
    "\074\uffc8\103\026\104\024\105\040\106\025\107\030\110" +
    "\032\111\031\112\033\001\002\000\004\075\ufff0\001\002" +
    "\000\004\074\323\001\002\000\004\075\ufff2\001\002\000" +
    "\004\075\ufff4\001\002\000\004\075\324\001\002\000\004" +
    "\055\325\001\002\000\004\074\326\001\002\000\004\075" +
    "\uffed\001\002\000\004\074\330\001\002\000\004\075\331" +
    "\001\002\000\004\077\332\001\002\000\004\074\333\001" +
    "\002\000\004\075\uffef\001\002\000\004\075\335\001\002" +
    "\000\006\031\337\052\336\001\002\000\004\074\344\001" +
    "\002\000\024\074\uffc8\103\026\104\024\105\040\106\025" +
    "\107\030\110\032\111\031\112\033\001\002\000\004\074" +
    "\341\001\002\000\004\075\uffeb\001\002\000\004\075\045" +
    "\001\002\000\004\002\uffea\001\002\000\004\002\uffec\001" +
    "\002\000\004\074\346\001\002\000\004\075\347\001\002" +
    "\000\004\101\350\001\002\000\004\074\351\001\002\000" +
    "\004\075\uffee\001\002\000\004\074\354\001\002\000\004" +
    "\075\ufff3\001\002\000\004\075\355\001\002\000\006\031" +
    "\357\052\356\001\002\000\004\074\364\001\002\000\024" +
    "\074\ufff6\103\ufff6\104\ufff6\105\ufff6\106\ufff6\107\ufff6\110" +
    "\ufff6\111\ufff6\112\ufff6\001\002\000\024\074\uffc8\103\026" +
    "\104\024\105\040\106\025\107\030\110\032\111\031\112" +
    "\033\001\002\000\004\074\362\001\002\000\004\075\045" +
    "\001\002\000\004\002\ufff5\001\002\000\004\002\ufff7\001" +
    "\002\000\004\002\ufff9\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\364\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\052\011\001\001\000\004\004" +
    "\015\001\001\000\002\001\001\000\002\001\001\000\030" +
    "\024\020\025\040\026\016\027\036\030\035\031\026\032" +
    "\034\033\021\034\017\035\022\036\033\001\001\000\002" +
    "\001\001\000\024\024\301\027\036\030\035\031\026\032" +
    "\034\033\021\034\017\035\022\036\033\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\054\042\001\001\000\006" +
    "\010\043\020\045\001\001\000\002\001\001\000\004\021" +
    "\235\001\001\000\002\001\001\000\004\021\051\001\001" +
    "\000\030\024\020\025\244\026\016\027\036\030\035\031" +
    "\026\032\034\033\021\034\017\035\022\036\033\001\001" +
    "\000\030\024\020\025\237\026\016\027\036\030\035\031" +
    "\026\032\034\033\021\034\017\035\022\036\033\001\001" +
    "\000\002\001\001\000\030\024\020\025\224\026\016\027" +
    "\036\030\035\031\026\032\034\033\021\034\017\035\022" +
    "\036\033\001\001\000\030\024\020\025\217\026\016\027" +
    "\036\030\035\031\026\032\034\033\021\034\017\035\022" +
    "\036\033\001\001\000\030\024\020\025\121\026\016\027" +
    "\036\030\035\031\026\032\034\033\021\034\017\035\022" +
    "\036\033\001\001\000\002\001\001\000\030\024\020\025" +
    "\114\026\016\027\036\030\035\031\026\032\034\033\021" +
    "\034\017\035\022\036\033\001\001\000\030\024\020\025" +
    "\107\026\016\027\036\030\035\031\026\032\034\033\021" +
    "\034\017\035\022\036\033\001\001\000\002\001\001\000" +
    "\030\024\020\025\076\026\016\027\036\030\035\031\026" +
    "\032\034\033\021\034\017\035\022\036\033\001\001\000" +
    "\030\024\020\025\071\026\016\027\036\030\035\031\026" +
    "\032\034\033\021\034\017\035\022\036\033\001\001\000" +
    "\030\024\020\025\064\026\016\027\036\030\035\031\026" +
    "\032\034\033\021\034\017\035\022\036\033\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\040\125\041\123\001\001\000\002\001" +
    "\001\000\004\047\126\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\030\024\020\025\131\026" +
    "\016\027\036\030\035\031\026\032\034\033\021\034\017" +
    "\035\022\036\033\001\001\000\002\001\001\000\006\042" +
    "\134\043\133\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\044\136\001\001\000\002\001\001\000\030\024" +
    "\020\025\174\026\016\027\036\030\035\031\026\032\034" +
    "\033\021\034\017\035\022\036\033\001\001\000\002\001" +
    "\001\000\030\024\020\025\142\026\016\027\036\030\035" +
    "\031\026\032\034\033\021\034\017\035\022\036\033\001" +
    "\001\000\002\001\001\000\010\045\145\050\147\051\152" +
    "\001\001\000\030\024\020\025\166\026\016\027\036\030" +
    "\035\031\026\032\034\033\021\034\017\035\022\036\033" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\030\024\020\025\161\026\016\027\036\030\035" +
    "\031\026\032\034\033\021\034\017\035\022\036\033\001" +
    "\001\000\002\001\001\000\004\050\153\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\046\176\050\147\051\200" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\050" +
    "\153\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\044" +
    "\207\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\047\214\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\020\227" +
    "\023\230\001\001\000\004\021\235\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\021\051\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\053\304\001\001\000" +
    "\006\006\305\013\307\001\001\000\002\001\001\000\012" +
    "\015\352\016\320\017\313\022\316\001\001\000\004\014" +
    "\311\001\001\000\012\015\321\016\320\017\313\022\316" +
    "\001\001\000\002\001\001\000\030\024\020\025\344\026" +
    "\016\027\036\030\035\031\026\032\034\033\021\034\017" +
    "\035\022\036\033\001\001\000\002\001\001\000\002\001" +
    "\001\000\030\024\020\025\326\026\016\027\036\030\035" +
    "\031\026\032\034\033\021\034\017\035\022\036\033\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\030\024\020\025\337\026\016\027\036\030\035\031" +
    "\026\032\034\033\021\034\017\035\022\036\033\001\001" +
    "\000\002\001\001\000\004\056\341\001\001\000\006\010" +
    "\342\020\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\055\357\001\001\000\030\024\020\025\360" +
    "\026\016\027\036\030\035\031\026\032\034\033\021\034" +
    "\017\035\022\036\033\001\001\000\002\001\001\000\006" +
    "\010\362\020\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AS_HTML$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AS_HTML$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AS_HTML$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public NodoDOM crearNodo(String nombre,String valor,int linea,int columna){
        NodoDOM nuevo = new NodoDOM(nombre,valor,linea,columna,action_obj.Index);
        action_obj.Index++;
        return nuevo;
    }

    //este metodo crear un nuevo nodo, lo agrega a la raiz actual y luego cambia la raizactual por el nuevo nodo creado
    public void m1(String nombre,String valor,int linea,int columna){
        NodoDOM nuevo = new NodoDOM(nombre,valor,linea,columna,action_obj.Index);
        action_obj.Index++;
        action_obj.tmpN.add(nuevo);
        action_obj.tmpN=nuevo;         //despues de crear el nuevo nodo se deja en la variable tmpN
    }


    //este metodo crear un nuevo nodo y simplemente se lo agrega a la raiz actual sin cambiarla
    public void m2(String nombre,String valor,int linea,int columna){
        NodoDOM nuevo = new NodoDOM(nombre,valor,linea,columna,action_obj.Index);
        action_obj.Index++;
        action_obj.tmpN.add(nuevo);
        action_obj.last=nuevo;
    }

    //Este metodo retorna la RAIZ del arbol  generado 
    public NodoDOM getRoot(){
        return action_obj.root;
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AS_HTML$actions {


    //se declaran variables globales etc.
    public int Index=1;
    public NodoDOM root;
    public NodoDOM tmpN ;
    public NodoDOM last ;

  private final AS_HTML parser;

  /** Constructor */
  CUP$AS_HTML$actions(AS_HTML parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AS_HTML$do_action(
    int                        CUP$AS_HTML$act_num,
    java_cup.runtime.lr_parser CUP$AS_HTML$parser,
    java.util.Stack            CUP$AS_HTML$stack,
    int                        CUP$AS_HTML$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AS_HTML$result;

      /* select the action based on the action number */
      switch (CUP$AS_HTML$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // cont_celda ::= IIMAGEN list_atts MAYQ MENQ FIMAGEN MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("cont_celda",38, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // cont_celda ::= IBOTON list_atts MAYQ MENQ FBOTON MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("cont_celda",38, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // cont_celda ::= I_D 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("cont_celda",38, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // contenidos_celdas ::= cont_celda 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidos_celdas",39, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // contenidos_celdas ::= contenidos_celdas cont_celda 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidos_celdas",39, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // att_alineado ::= ALINEADO IGUAL STRING_LITERAL 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		token y = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = parser.crearNodo("alineado",y.getCadena(),x.getLinea(),x.getColumna()); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("att_alineado",28, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // att_ancho ::= ANCHO IGUAL STRING_LITERAL 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		token y = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = parser.crearNodo("ancho",y.getCadena(),x.getLinea(),x.getColumna()); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("att_ancho",27, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // att_alto ::= ALTO IGUAL STRING_LITERAL 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		token y = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = parser.crearNodo("alto",y.getCadena(),x.getLinea(),x.getColumna()); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("att_alto",26, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // att_grupo ::= GRUPO IGUAL STRING_LITERAL 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		token y = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = parser.crearNodo("grupo",y.getCadena(),x.getLinea(),x.getColumna()); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("att_grupo",25, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // att_id ::= ID IGUAL STRING_LITERAL 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		token y = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = parser.crearNodo("id",y.getCadena(),x.getLinea(),x.getColumna()); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("att_id",24, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // att_valor ::= VALOR IGUAL STRING_LITERAL 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		token y = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = parser.crearNodo("valor",y.getCadena(),x.getLinea(),x.getColumna()); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("att_valor",23, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // att_click ::= CLICK IGUAL STRING_LITERAL APAR CPAR 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token y = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
		 RESULT = parser.crearNodo("click",y.getCadena(),x.getLinea(),x.getColumna()); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("att_click",22, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // att_ruta ::= RUTA IGUAL STRING_LITERAL 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		token y = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = parser.crearNodo("ruta",y.getCadena(),x.getLinea(),x.getColumna()); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("att_ruta",21, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // atributo ::= att_alineado 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r;   
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("atributo",18, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // atributo ::= att_ancho 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r;   
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("atributo",18, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // atributo ::= att_alto 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r;   
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("atributo",18, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // atributo ::= att_grupo 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r;   
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("atributo",18, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // atributo ::= att_id 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r;   
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("atributo",18, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // atributo ::= att_valor 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r;   
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("atributo",18, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // atributo ::= att_click 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r;   
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("atributo",18, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // atributo ::= att_ruta 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r;   
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("atributo",18, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // list_atts2 ::= atributo PYC 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).right;
		NodoDOM x = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).value;
		 
                                RESULT = parser.crearNodo("propiedades","",0,0); 
                                RESULT.add(x);
                            
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("list_atts2",20, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // list_atts2 ::= list_atts2 atributo PYC 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		NodoDOM x = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).right;
		NodoDOM y = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).value;
		
                                x.add(y);
                                RESULT=x;    
                            
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("list_atts2",20, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // list_atts ::= list_atts2 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM x = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		   RESULT = x;  
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("list_atts",19, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // list_atts ::= 
            {
              NodoDOM RESULT =null;
		    RESULT = parser.crearNodo("propiedades","",0,0);   
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("list_atts",19, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // contenidopanel ::= MENQ FPANEL MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidopanel",17, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // contenidopanel ::= etiquetas_cuerpo MENQ FPANEL MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidopanel",17, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // contenidoct ::= MENQ FCT MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidoct",35, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // contenidoct ::= contenidos_celdas MENQ FCT MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidoct",35, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // contenidocb ::= MENQ FCB MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidocb",36, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // contenidocb ::= contenidos_celdas MENQ FCB MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidocb",36, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // et_cb_ct ::= ICT list_atts MAYQ contenidoct 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cb_ct",34, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // et_cb_ct ::= ICB list_atts MAYQ contenidocb 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cb_ct",34, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // etiquetasfila ::= MENQ et_cb_ct 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetasfila",33, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // etiquetasfila ::= etiquetasfila MENQ et_cb_ct 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetasfila",33, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // contenidofila ::= MENQ FFIL_T MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidofila",32, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // contenidofila ::= etiquetasfila MENQ FFIL_T MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidofila",32, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // et_fila ::= IFIL_T list_atts MAYQ contenidofila 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_fila",37, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // etiquetastabla ::= MENQ et_fila 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetastabla",31, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // etiquetastabla ::= etiquetastabla MENQ et_fila 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetastabla",31, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // contenidotabla ::= MENQ FTABLA MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidotabla",30, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // contenidotabla ::= etiquetastabla MENQ FTABLA MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidotabla",30, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // et_cuerpo ::= ISALTOF 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // et_cuerpo ::= ISPINNER list_atts MAYQ MENQ FSPINNER MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // et_cuerpo ::= ICAJA list_atts MAYQ MENQ FCAJA MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // et_cuerpo ::= ICAJA_TEXTO list_atts MAYQ MENQ FCAJA_TEXTO MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // et_cuerpo ::= ITEXTO_A list_atts MAYQ MENQ FTEXTO_A MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // et_cuerpo ::= ITABLA list_atts MAYQ contenidotabla 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // et_cuerpo ::= IENLACE list_atts MAYQ MENQ FENLACE MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // et_cuerpo ::= IBOTON list_atts MAYQ MENQ FBOTON MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // et_cuerpo ::= IIMAGEN list_atts MAYQ MENQ FIMAGEN MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // et_cuerpo ::= ITEXTO list_atts MAYQ MENQ FTEXTO MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // et_cuerpo ::= IPANEL list_atts MAYQ contenidopanel 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_cuerpo",15, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // etiquetas_cuerpo ::= MENQ et_cuerpo 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetas_cuerpo",14, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // etiquetas_cuerpo ::= etiquetas_cuerpo MENQ et_cuerpo 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetas_cuerpo",14, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // contenidocuerpo ::= MENQ FCUERPO MAYQ MENQ FHTML MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidocuerpo",6, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // contenidocuerpo ::= etiquetas_cuerpo MENQ FCUERPO MAYQ MENQ FHTML MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidocuerpo",6, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-6)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // contenidocss ::= FCSS MAYQ MENQ FENCABEZADO MAYQ MENQ FHTML MAYQ FCSS MAYQ MENQ FENCABEZADO MAYQ MENQ ICUERPO list_atts MAYQ contenidocuerpo 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidocss",8, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-17)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // fin_encabezado ::= MENQ FENCABEZADO MAYQ MENQ ICUERPO list_atts MAYQ NT$4 contenidocuerpo 
            {
              NodoDOM RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (NodoDOM) ((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).value;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("fin_encabezado",10, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-8)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // NT$4 ::= 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
 parser.m1("cuerpo","",x.getLinea(),x.getColumna());
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("NT$4",44, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // fin_encabezado ::= MENQ FENCABEZADO MAYQ MENQ FHTML MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("fin_encabezado",10, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // etiquetatitulo ::= ITITULO MAYQ MENQ FTITULO MAYQ 
            {
              NodoDOM RESULT =null;
		 RESULT = parser.crearNodo("titulo","",0,0); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetatitulo",16, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // etiquetacjs ::= ICSS list_atts MAYQ MENQ FCSS MAYQ 
            {
              NodoDOM RESULT =null;
		 RESULT = parser.crearNodo("ccss","",0,0); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetacjs",13, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // etiquetacss ::= ICJS list_atts MAYQ MENQ FCJS MAYQ 
            {
              NodoDOM RESULT =null;
		 RESULT = parser.crearNodo("cjs","",0,0); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetacss",12, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // et_encabezado ::= etiquetatitulo 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r; 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_encabezado",11, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // et_encabezado ::= etiquetacjs 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r; 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_encabezado",11, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // et_encabezado ::= etiquetacss 
            {
              NodoDOM RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM r = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 RESULT = r; 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("et_encabezado",11, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // etiquetas_encabezado ::= MENQ et_encabezado 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM x = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 last.add(x); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetas_encabezado",9, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // etiquetas_encabezado ::= etiquetas_encabezado MENQ et_encabezado 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		NodoDOM x = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
		 last.add(x); 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("etiquetas_encabezado",9, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // contenidoencabezado ::= MENQ FENCABEZADO MAYQ MENQ ICUERPO NT$3 list_atts MAYQ contenidocuerpo 
            {
              NodoDOM RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (NodoDOM) ((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).value;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidoencabezado",4, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-8)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$3 ::= 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.peek()).value;
 parser.m1("cuerpo","",x.getLinea(),x.getColumna());
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("NT$3",43, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // contenidoencabezado ::= MENQ FENCABEZADO MAYQ MENQ FHTML MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidoencabezado",4, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // contenidoencabezado ::= etiquetas_encabezado fin_encabezado 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidoencabezado",4, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // contenidohtml ::= FHTML MAYQ 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidohtml",2, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // contenidohtml ::= ICUERPO list_atts MAYQ NT$2 contenidocuerpo 
            {
              NodoDOM RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (NodoDOM) ((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).value;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidohtml",2, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NT$2 ::= 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
parser.m2("cuerpo","",x.getLinea(),x.getColumna());
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("NT$2",42, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // contenidohtml ::= IENCABEZADO MAYQ NT$1 contenidoencabezado 
            {
              NodoDOM RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (NodoDOM) ((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)).value;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("contenidohtml",2, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-3)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$1 ::= 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).value;
parser.m2("encabezado","",x.getLinea(),x.getColumna());
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("NT$1",41, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // raiz ::= MENQ IHTML MAYQ MENQ NT$0 contenidohtml 
            {
              NodoDOM RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (NodoDOM) ((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-4)).value;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("raiz",1, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-5)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // NT$0 ::= 
            {
              NodoDOM RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).right;
		token x = (token)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-2)).value;
 root = parser.crearNodo("chtml","",x.getLinea(),x.getColumna());  tmpN=root; 
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("NT$0",40, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= raiz 
            {
              NodoDOM RESULT =null;

              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          return CUP$AS_HTML$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).right;
		NodoDOM start_val = (NodoDOM)((java_cup.runtime.Symbol) CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)).value;
		RESULT = start_val;
              CUP$AS_HTML$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.elementAt(CUP$AS_HTML$top-1)), ((java_cup.runtime.Symbol)CUP$AS_HTML$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AS_HTML$parser.done_parsing();
          return CUP$AS_HTML$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

